/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author User-1
 */
public class Studentlogin extends javax.swing.JFrame {

    /**
     * Creates new form Studentlogin
     */
    public Studentlogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_studetail = new javax.swing.JButton();
        btn_newaddmission = new javax.swing.JButton();
        btn_back5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));

        btn_studetail.setBackground(new java.awt.Color(0, 204, 204));
        btn_studetail.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_studetail.setForeground(new java.awt.Color(102, 102, 102));
        btn_studetail.setText("Student s' Details Form");
        btn_studetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studetailActionPerformed(evt);
            }
        });

        btn_newaddmission.setBackground(new java.awt.Color(0, 204, 204));
        btn_newaddmission.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_newaddmission.setForeground(new java.awt.Color(102, 102, 102));
        btn_newaddmission.setText("New Addmission Form");
        btn_newaddmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newaddmissionActionPerformed(evt);
            }
        });

        btn_back5.setBackground(new java.awt.Color(255, 255, 255));
        btn_back5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_back5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        btn_back5.setText("Back");
        btn_back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_studetail)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_back5)
                        .addComponent(btn_newaddmission)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btn_studetail)
                .addGap(18, 18, 18)
                .addComponent(btn_newaddmission)
                .addGap(95, 95, 95)
                .addComponent(btn_back5)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studetailActionPerformed
       this.hide();
        student frm = new student();
        frm.setVisible(true);
    }//GEN-LAST:event_btn_studetailActionPerformed

    private void btn_newaddmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newaddmissionActionPerformed
       this.hide();
        NewAddmission frm = new NewAddmission();
        frm.setVisible(true);
    }//GEN-LAST:event_btn_newaddmissionActionPerformed

    private void btn_back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back5ActionPerformed
        this.hide();
        AdminPage1 frm = new AdminPage1();
        frm.setVisible(true);
    }//GEN-LAST:event_btn_back5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back5;
    private javax.swing.JButton btn_newaddmission;
    private javax.swing.JButton btn_studetail;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
