/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User-1
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher2
     */
    public Teacher() {
        initComponents();
        setLocationRelativeTo(null);
        scrolPaneOne.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrolPaneOne = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbTgender = new javax.swing.JComboBox<>();
        tTregno = new javax.swing.JTextField();
        tTfullname = new javax.swing.JTextField();
        tTdob = new javax.swing.JTextField();
        tTaddress = new javax.swing.JTextField();
        tTapoimentdate = new javax.swing.JTextField();
        tTsubject = new javax.swing.JTextField();
        tTinchargeclass = new javax.swing.JTextField();
        tTtepno = new javax.swing.JTextField();
        tTgname = new javax.swing.JTextField();
        tTgtelephoneno = new javax.swing.JTextField();
        tTsearch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btnTdelete = new javax.swing.JButton();
        btn_rest1 = new javax.swing.JButton();
        btn_can4 = new javax.swing.JButton();
        btn_back5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher s' Details Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Registration Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date Of Birth");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Apoiment Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Subject");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Incharge Class");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Telephone Number");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Guardian s' Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Guardian s' Telephone Number");

        cbTgender.setBackground(new java.awt.Color(0, 153, 153));
        cbTgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTgender.setForeground(new java.awt.Color(204, 204, 204));
        cbTgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        tTsearch.setBackground(new java.awt.Color(0, 153, 153));
        tTsearch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tTsearch.setForeground(new java.awt.Color(204, 204, 204));
        tTsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/search.png"))); // NOI18N
        tTsearch.setText("Search");
        tTsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTsearchActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("YY-MM-DD");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("YY-MM-DD");

        btn_update.setBackground(new java.awt.Color(51, 255, 0));
        btn_update.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/7030130_ui basic_upload_app_file_document_icon (2).png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btnTdelete.setBackground(new java.awt.Color(255, 0, 0));
        btnTdelete.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnTdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/3669361_delete_ic_icon (1).png"))); // NOI18N
        btnTdelete.setText("Delete");
        btnTdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTdeleteActionPerformed(evt);
            }
        });

        btn_rest1.setBackground(new java.awt.Color(0, 153, 255));
        btn_rest1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_rest1.setText("Reset");
        btn_rest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rest1ActionPerformed(evt);
            }
        });

        btn_can4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_can4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancel.png"))); // NOI18N
        btn_can4.setText("Cancel");
        btn_can4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_can4ActionPerformed(evt);
            }
        });

        btn_back5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_back5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        btn_back5.setText("Back");
        btn_back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbTgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tTfullname, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                                .addComponent(tTaddress)
                                .addComponent(tTsubject)
                                .addComponent(tTinchargeclass)
                                .addComponent(tTtepno)
                                .addComponent(tTgname)
                                .addComponent(tTgtelephoneno)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(tTregno)
                                    .addGap(18, 18, 18)
                                    .addComponent(tTsearch))
                                .addComponent(tTdob, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tTapoimentdate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btn_back5)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTdelete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_rest1)
                        .addGap(27, 27, 27)
                        .addComponent(btn_can4)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tTregno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTsearch))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tTfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tTdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbTgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6))
                    .addComponent(tTaddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tTapoimentdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tTsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tTinchargeclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tTtepno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tTgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tTgtelephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(btnTdelete)
                    .addComponent(btn_rest1)
                    .addComponent(btn_can4)
                    .addComponent(btn_back5))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        scrolPaneOne.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPaneOne, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrolPaneOne, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTsearchActionPerformed
        Connection connection;
        PreparedStatement ps;
       
        try{
            Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
            ps = conn.prepareStatement("SELECT * FROM teacher WHERE  RegistrationNumber=? ");
            ps.setString(1, tTregno.getText());
           
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next())
            {
                String value1=rs.getString("FullName");
                tTfullname.setText(value1);
                String value2=rs.getString("DateofBirth");
               tTdob.setText(value2);
                String value3=rs.getString("Gender");
                cbTgender.setSelectedItem(value3);
                String value4=rs.getString("Address");
               tTaddress.setText(value4);
                String value5=rs.getString("ApoimentDate");
                tTapoimentdate.setText(value5);
                String value6=rs.getString("Subject");
                tTsubject.setText(value6);
                String value7=rs.getString("InchargeClass");
                tTinchargeclass.setText(value7);
                String value8=rs.getString("TelephoneNumber");
                tTtepno.setText(value8);
                String value9=rs.getString("GuardiansName");
                tTgname.setText(value9);
                String value10=rs.getString("GuardiansTelephoneNumber");
              tTgtelephoneno.setText(value10);
                
            }else{
            JOptionPane.showMessageDialog(this,"Index No is Invalid");
            
            }
            
            } catch (SQLException ex) {
                Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_tTsearchActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
       String RegistrationNumber=tTregno.getText();
            String value1=tTfullname.getText();
            String value2=tTdob.getText();
            String value3=cbTgender.getSelectedItem().toString();
            String value4=tTaddress.getText();
            String value5=tTapoimentdate.getText();
            String value6=tTsubject.getText();
            String value7=tTinchargeclass.getText();
            String value8=tTtepno.getText();
            String value9=tTgname.getText();
            String value10=tTgtelephoneno.getText();
            
           try{  
            String sql = "Update teacher set FullName='"+value1+"' ,DateofBirth='"+value2+"',Gender='"+value3+"' ,Address='"+value4+"' ,ApoimentDate='"+value5+"' ,Subject='"+value6+"' ,InchargeClass='"+value7+"' ,TelephoneNumber='"+value8+"' ,GuardiansName='"+value9+"' ,GuardiansTelephoneNumber='"+value10+"' where RegistrationNumber='"+RegistrationNumber+"' "; 
            
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
            PreparedStatement ps= conn.prepareStatement(sql);
            ps.execute();
             JOptionPane.showMessageDialog(null,"Updated");
            
            
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
            
            
            
        } 
            
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btnTdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTdeleteActionPerformed
          String sql="DELETE FROM teacher WHERE FullName=?" ;
        try{
             
             Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
             PreparedStatement ps= conn.prepareStatement(sql); 
             ps.setString(1, tTfullname.getText());
             ps.execute();
             JOptionPane.showMessageDialog(null,"Deleted");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
            
            
        }
    }//GEN-LAST:event_btnTdeleteActionPerformed

    private void btn_can4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_can4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_can4ActionPerformed

    private void btn_rest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rest1ActionPerformed
       tTregno.setText("");
        tTfullname.setText("");
        tTdob.setText("");
        cbTgender.setSelectedItem("");
        tTaddress.setText("");
        tTapoimentdate.setText("");
        tTsubject.setText("");
        tTinchargeclass.setText("");
        tTtepno.setText("");
        tTgname.setText("");
        tTgtelephoneno.setText("");
        
    }//GEN-LAST:event_btn_rest1ActionPerformed

    private void btn_back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back5ActionPerformed
        this.hide();
        Teacherlogin frm = new Teacherlogin();
        frm.setVisible(true);
    }//GEN-LAST:event_btn_back5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTdelete;
    private javax.swing.JButton btn_back5;
    private javax.swing.JButton btn_can4;
    private javax.swing.JButton btn_rest1;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbTgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrolPaneOne;
    private javax.swing.JTextField tTaddress;
    private javax.swing.JTextField tTapoimentdate;
    private javax.swing.JTextField tTdob;
    private javax.swing.JTextField tTfullname;
    private javax.swing.JTextField tTgname;
    private javax.swing.JTextField tTgtelephoneno;
    private javax.swing.JTextField tTinchargeclass;
    private javax.swing.JTextField tTregno;
    private javax.swing.JButton tTsearch;
    private javax.swing.JTextField tTsubject;
    private javax.swing.JTextField tTtepno;
    // End of variables declaration//GEN-END:variables
}
